# Generated by Django 5.0.2 on 2024-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_position', models.CharField(max_length=50)),
                ('member_image', models.ImageField(upload_to='../static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Presedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_name', models.CharField(max_length=50)),
                ('pres_position', models.CharField(choices=[('Presedent', 'Presedent'), ('Vice Presedent', 'Vice Presedent')], default='Presedent', max_length=50)),
                ('pres_image', models.ImageField(upload_to='../static/images')),
            ],
        ),
    ]
