# Generated by Django 5.0.2 on 2024-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='presedent',
            name='pres_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
