# Generated by Django 5.0.2 on 2024-02-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Images',
        ),
    ]
