# Generated by Django 5.0.2 on 2024-02-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_gallery_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
