# Generated by Django 5.0.2 on 2024-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField()),
                ('event_image', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
