# Generated by Django 5.0.2 on 2024-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('doc', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
